"""daniel-madriz db init

Revision ID: 8f753d70f5c8
Revises: 
Create Date: 2025-09-03 03:12:21.570512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f753d70f5c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danielmadriz_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_person_full_name', 'danielmadriz_person', ['full_name'], unique=False)
    op.create_table('danielmadriz_family_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['danielmadriz_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_family_relation_person_relation', 'danielmadriz_family_relation', ['person_id', 'relation'], unique=False)
    op.create_table('danielmadriz_favorite_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['danielmadriz_person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'food', name='uq_person_food')
    )
    op.create_index('idx_favorite_food_food', 'danielmadriz_favorite_food', ['food'], unique=False)
    op.create_table('danielmadriz_hobby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('hobby', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['danielmadriz_person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'hobby', name='uq_person_hobby')
    )
    op.create_index('idx_hobby_hobby', 'danielmadriz_hobby', ['hobby'], unique=False)
    op.create_table('danielmadriz_physical_profile',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('eye_color', sa.String(length=50), nullable=True),
    sa.Column('hair_color', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['danielmadriz_person.id'], ),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_index('idx_physical_profile_age', 'danielmadriz_physical_profile', ['age'], unique=False)
    op.create_index('idx_physical_profile_eye_color', 'danielmadriz_physical_profile', ['eye_color'], unique=False)
    op.create_index('idx_physical_profile_hair_color', 'danielmadriz_physical_profile', ['hair_color'], unique=False)
    op.create_index('idx_physical_profile_nationality', 'danielmadriz_physical_profile', ['nationality'], unique=False)
    op.create_table('danielmadriz_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['danielmadriz_person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'degree', 'institution', name='uq_person_degree_institution')
    )
    op.create_index('idx_study_degree', 'danielmadriz_study', ['degree'], unique=False)
    op.create_index('idx_study_institution', 'danielmadriz_study', ['institution'], unique=False)
    op.drop_table('monsters_list_crisarias')
    op.drop_table('monster_majocr')
    op.drop_table('castroulloaaaron_allmonsters')
    op.drop_table('monster_list_majocr')
    op.drop_table('castroulloaaaron_monsters')
    op.drop_table('randallbrenes_dnd_monsters')
    op.drop_table('alfonsovso_monsters_index')
    op.drop_table('motivational_phrases')
    op.drop_table('randymorales_monster_list_cache')
    op.drop_table('monsters_crisarias')
    op.drop_table('kevinWalshMunozMonsters')
    op.drop_table('monsters_danrodjim')
    op.drop_table('kevinWalshMunozMonster')
    op.drop_table('alembic_version')
    op.drop_table('randymorales_monster_cache')
    op.drop_table('alfonsovso_monsters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alfonsovso_monsters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alfonsovso_monsters_pkey')),
    sa.UniqueConstraint('index', name=op.f('alfonsovso_monsters_index_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('randymorales_monster_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('monster_index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('monster_data', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('randymorales_monster_cache_pkey')),
    sa.UniqueConstraint('monster_index', name=op.f('randymorales_monster_cache_monster_index_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('kevinWalshMunozMonster',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('index', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('size', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alignment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('armor_class', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hit_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hit_dice', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hit_points_roll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('speed', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dexterity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('constitution', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intelligence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wisdom', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('charisma', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proficiencies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('damage_vulnerabilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('damage_resistances', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('damage_immunities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('condition_immunities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('senses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('challenge_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proficiency_bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('special_abilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('legendary_actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('forms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('kevinWalshMunozMonster_pkey')),
    sa.UniqueConstraint('index', name=op.f('kevinWalshMunozMonster_index_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('monsters_danrodjim',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('monsters_danrodjim_pkey')),
    sa.UniqueConstraint('index', name=op.f('monsters_danrodjim_index_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('monsters_danrodjim_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('url', name=op.f('monsters_danrodjim_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('kevinWalshMunozMonsters',
    sa.Column('index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('index', name=op.f('kevinWalshMunozMonsters_pkey'))
    )
    op.create_table('monsters_crisarias',
    sa.Column('index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name=op.f('monsters_crisarias_pkey'))
    )
    op.create_table('randymorales_monster_list_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('list_data', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('randymorales_monster_list_cache_pkey')),
    sa.UniqueConstraint('resource', name=op.f('randymorales_monster_list_cache_resource_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('motivational_phrases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phrase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('motivational_phrases_pkey'))
    )
    op.create_table('alfonsovso_monsters_index',
    sa.Column('index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name=op.f('alfonsovso_monsters_index_pkey'))
    )
    op.create_table('randallbrenes_dnd_monsters',
    sa.Column('index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('json_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name=op.f('randallbrenes_dnd_monsters_pkey'))
    )
    op.create_table('castroulloaaaron_monsters',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('json_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('castroulloaaaron_monsters_pkey'))
    )
    op.create_table('monster_list_majocr',
    sa.Column('index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('index', name=op.f('monster_list_majocr_pkey'))
    )
    op.create_table('castroulloaaaron_allmonsters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('json_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('castroulloaaaron_allmonsters_pkey'))
    )
    op.create_table('monster_majocr',
    sa.Column('index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('index', name=op.f('monster_majocr_pkey'))
    )
    op.create_table('monsters_list_crisarias',
    sa.Column('index', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name=op.f('monsters_list_crisarias_pkey'))
    )
    op.drop_index('idx_study_institution', table_name='danielmadriz_study')
    op.drop_index('idx_study_degree', table_name='danielmadriz_study')
    op.drop_table('danielmadriz_study')
    op.drop_index('idx_physical_profile_nationality', table_name='danielmadriz_physical_profile')
    op.drop_index('idx_physical_profile_hair_color', table_name='danielmadriz_physical_profile')
    op.drop_index('idx_physical_profile_eye_color', table_name='danielmadriz_physical_profile')
    op.drop_index('idx_physical_profile_age', table_name='danielmadriz_physical_profile')
    op.drop_table('danielmadriz_physical_profile')
    op.drop_index('idx_hobby_hobby', table_name='danielmadriz_hobby')
    op.drop_table('danielmadriz_hobby')
    op.drop_index('idx_favorite_food_food', table_name='danielmadriz_favorite_food')
    op.drop_table('danielmadriz_favorite_food')
    op.drop_index('idx_family_relation_person_relation', table_name='danielmadriz_family_relation')
    op.drop_table('danielmadriz_family_relation')
    op.drop_index('idx_person_full_name', table_name='danielmadriz_person')
    op.drop_table('danielmadriz_person')
    # ### end Alembic commands ###
