"""add models for exercise 2

Revision ID: 7f4fb32671cc
Revises: 
Create Date: 2025-08-31 13:46:13.977079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4fb32671cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('eye_color', sa.Text(), nullable=True),
    sa.Column('hair_color', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_person_age', 'person', ['age'], unique=False)
    op.create_index('ix_person_eye_color', 'person', ['eye_color'], unique=False)
    op.create_index('ix_person_hair_color', 'person', ['hair_color'], unique=False)
    op.create_index('ix_person_height_cm', 'person', ['height_cm'], unique=False)
    op.create_index('ix_person_nationality', 'person', ['nationality'], unique=False)
    op.create_index('ix_person_weight_kg', 'person', ['weight_kg'], unique=False)
    op.create_table('family',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_family_relation', 'family', ['relation'], unique=False)
    op.create_table('favorite_food',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('food', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_favorite_food_food', 'favorite_food', ['food'], unique=False)
    op.create_table('hobby',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('hobby', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hobby_hobby', 'hobby', ['hobby'], unique=False)
    op.create_table('study',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.Text(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_study_degree', 'study', ['degree'], unique=False)
    op.create_index('ix_study_institution', 'study', ['institution'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_study_institution', table_name='study')
    op.drop_index('ix_study_degree', table_name='study')
    op.drop_table('study')
    op.drop_index('ix_hobby_hobby', table_name='hobby')
    op.drop_table('hobby')
    op.drop_index('ix_favorite_food_food', table_name='favorite_food')
    op.drop_table('favorite_food')
    op.drop_index('ix_family_relation', table_name='family')
    op.drop_table('family')
    op.drop_index('ix_person_weight_kg', table_name='person')
    op.drop_index('ix_person_nationality', table_name='person')
    op.drop_index('ix_person_height_cm', table_name='person')
    op.drop_index('ix_person_hair_color', table_name='person')
    op.drop_index('ix_person_eye_color', table_name='person')
    op.drop_index('ix_person_age', table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
