"""daniel madriz entities update

Revision ID: 02670b1c0a3a
Revises: 8768813f7d21
Create Date: 2025-08-27 22:40:00.617644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02670b1c0a3a'
down_revision: Union[str, Sequence[str], None] = '8768813f7d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('danielmadriz_monsters', sa.Column('index', sa.String(), nullable=False))
    op.add_column('danielmadriz_monsters', sa.Column('name', sa.String(), nullable=False))
    op.add_column('danielmadriz_monsters', sa.Column('url', sa.String(), nullable=False))
    op.add_column('danielmadriz_monsters', sa.Column('data', sa.JSON(), nullable=False))
    op.drop_column('danielmadriz_monsters', 'id')
    op.drop_column('danielmadriz_monsters', 'json_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('danielmadriz_monsters', sa.Column('json_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('danielmadriz_monsters', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('danielmadriz_monsters', 'data')
    op.drop_column('danielmadriz_monsters', 'url')
    op.drop_column('danielmadriz_monsters', 'name')
    op.drop_column('danielmadriz_monsters', 'index')
    # ### end Alembic commands ###
