"""Created randallbrenes_dnd_monsters table

Revision ID: 0d4c29e248d1
Revises: aa75144a150e
Create Date: 2025-08-21 21:23:04.461588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d4c29e248d1'
down_revision: Union[str, Sequence[str], None] = 'aa75144a150e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('randallbrenes_dnd_monsters',
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('armor_class', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('hit_dice', sa.String(), nullable=True),
    sa.Column('hit_points_roll', sa.String(), nullable=True),
    sa.Column('speed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.String(), nullable=True),
    sa.Column('constitution', sa.String(), nullable=True),
    sa.Column('intelligence', sa.String(), nullable=True),
    sa.Column('wisdom', sa.String(), nullable=True),
    sa.Column('charisma', sa.String(), nullable=True),
    sa.Column('proficiencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('damage_vulnerabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('damage_resistances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('damage_immunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('condition_immunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('senses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('challenge_rating', sa.Integer(), nullable=True),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('special_abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legendary_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('forms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('randallbrenes_dnd_monsters')
    # ### end Alembic commands ###
