"""Created randallbrenes_dnd_monsters table

Revision ID: 0d4c29e248d1
Revises: aa75144a150e
Create Date: 2025-08-21 21:23:04.461588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d4c29e248d1'
down_revision: Union[str, Sequence[str], None] = '575f079b84bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'randallbrenes_dnd_monsters',
        sa.Column('index', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('randallbrenes_dnd_monsters')
    # ### end Alembic commands ###