"""add monsters + monster_details v8

Revision ID: 36212e46cc4d
Revises: aa75144a150e
Create Date: 2025-08-26 00:11:32.948483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36212e46cc4d"
down_revision: Union[str, Sequence[str], None] = "1bbdc41ad0e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjus t! ###
    op.create_table('odkeyo_monsters',
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('odkeyo_monster_details',
    sa.Column('monster_index', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['monster_index'], ['odkeyo_monsters.index'], ),
    sa.PrimaryKeyConstraint('monster_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odkeyo_monster_details')
    op.drop_table('odkeyo_monsters')
    # ### end Alembic commands ###
