"""Initial migration

Revision ID: 3a97cf9f8b72
Revises: aa75144a150e
Create Date: 2025-08-26 19:29:25.602886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a97cf9f8b72'
down_revision: Union[str, Sequence[str], None] = 'aa75144a150e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('andresnboza_monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('armor_class', sa.String(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('hit_dice', sa.String(), nullable=True),
    sa.Column('hit_points_roll', sa.String(), nullable=True),
    sa.Column('speed', sa.String(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('proficiencies', sa.String(), nullable=True),
    sa.Column('damage_vulnerabilities', sa.String(), nullable=True),
    sa.Column('damage_resistances', sa.String(), nullable=True),
    sa.Column('damage_immunities', sa.String(), nullable=True),
    sa.Column('condition_immunities', sa.String(), nullable=True),
    sa.Column('senses', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('challenge_rating', sa.Integer(), nullable=True),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('special_abilities', sa.String(), nullable=True),
    sa.Column('actions', sa.String(), nullable=True),
    sa.Column('legendary_actions', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('forms', sa.String(), nullable=True),
    sa.Column('reactions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('andresnboza_monster')
    # ### end Alembic commands ###
