"""andresnboza migration

Revision ID: 643fd6d7515e
Revises: 
Create Date: 2025-08-27 19:26:47.399883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '643fd6d7515e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('andresnboza_monster',
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('armor_class', sa.String(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('hit_dice', sa.String(), nullable=True),
    sa.Column('hit_points_roll', sa.String(), nullable=True),
    sa.Column('speed', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('castroulloaaaron_allmonsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('castroulloaaaron_monsters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kevinWalshMunozMonster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('alignment', sa.Text(), nullable=True),
    sa.Column('armor_class', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('hit_dice', sa.Text(), nullable=True),
    sa.Column('hit_points_roll', sa.Text(), nullable=True),
    sa.Column('speed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('proficiencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('damage_vulnerabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('damage_resistances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('damage_immunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('condition_immunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('senses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('challenge_rating', sa.Integer(), nullable=True),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('special_abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legendary_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('forms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('kevinWalshMunozMonsters',
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('monster_list_majocr',
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('monster_majocr',
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('monsters_danrodjim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('motivational_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randallbrenes_dnd_monsters',
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('json_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('randallbrenes_dnd_monsters')
    op.drop_table('motivational_phrases')
    op.drop_table('monsters_danrodjim')
    op.drop_table('monster_majocr')
    op.drop_table('monster_list_majocr')
    op.drop_table('kevinWalshMunozMonsters')
    op.drop_table('kevinWalshMunozMonster')
    op.drop_table('castroulloaaaron_monsters')
    op.drop_table('castroulloaaaron_allmonsters')
    op.drop_table('andresnboza_monster')
    # ### end Alembic commands ###
