"""Add monster columns

Revision ID: 71a437db6003
Revises: 2d90d3da552a
Create Date: 2025-08-26 07:32:50.335942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a437db6003'
down_revision: Union[str, Sequence[str], None] = '2d90d3da552a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('andresnboza_monster', sa.Column('index', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('size', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('type', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('alignment', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('armor_class', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('hit_points', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('hit_dice', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('hit_points_roll', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('speed', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('strength', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('dexterity', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('constitution', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('intelligence', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('wisdom', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('charisma', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('proficiencies', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('damage_vulnerabilities', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('damage_resistances', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('damage_immunities', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('condition_immunities', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('senses', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('challenge_rating', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('proficiency_bonus', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('special_abilities', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('actions', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('legendary_actions', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('image', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('url', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('forms', sa.String(), nullable=True))
    op.add_column('andresnboza_monster', sa.Column('reactions', sa.String(), nullable=True))
    op.alter_column('andresnboza_monster', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('andresnboza_monster', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('andresnboza_monster', 'reactions')
    op.drop_column('andresnboza_monster', 'forms')
    op.drop_column('andresnboza_monster', 'updated_at')
    op.drop_column('andresnboza_monster', 'url')
    op.drop_column('andresnboza_monster', 'image')
    op.drop_column('andresnboza_monster', 'legendary_actions')
    op.drop_column('andresnboza_monster', 'actions')
    op.drop_column('andresnboza_monster', 'special_abilities')
    op.drop_column('andresnboza_monster', 'xp')
    op.drop_column('andresnboza_monster', 'proficiency_bonus')
    op.drop_column('andresnboza_monster', 'challenge_rating')
    op.drop_column('andresnboza_monster', 'languages')
    op.drop_column('andresnboza_monster', 'senses')
    op.drop_column('andresnboza_monster', 'condition_immunities')
    op.drop_column('andresnboza_monster', 'damage_immunities')
    op.drop_column('andresnboza_monster', 'damage_resistances')
    op.drop_column('andresnboza_monster', 'damage_vulnerabilities')
    op.drop_column('andresnboza_monster', 'proficiencies')
    op.drop_column('andresnboza_monster', 'charisma')
    op.drop_column('andresnboza_monster', 'wisdom')
    op.drop_column('andresnboza_monster', 'intelligence')
    op.drop_column('andresnboza_monster', 'constitution')
    op.drop_column('andresnboza_monster', 'dexterity')
    op.drop_column('andresnboza_monster', 'strength')
    op.drop_column('andresnboza_monster', 'speed')
    op.drop_column('andresnboza_monster', 'hit_points_roll')
    op.drop_column('andresnboza_monster', 'hit_dice')
    op.drop_column('andresnboza_monster', 'hit_points')
    op.drop_column('andresnboza_monster', 'armor_class')
    op.drop_column('andresnboza_monster', 'alignment')
    op.drop_column('andresnboza_monster', 'type')
    op.drop_column('andresnboza_monster', 'size')
    op.drop_column('andresnboza_monster', 'index')
    # ### end Alembic commands ###
