"""daniel madriz entities creation

Revision ID: 8768813f7d21
Revises: 0d4c29e248d1
Create Date: 2025-08-27 22:07:44.929464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8768813f7d21'
down_revision: Union[str, Sequence[str], None] = '0d4c29e248d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danielmadriz_allmonsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('danielmadriz_monsters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('randallbrenes_dnd_monsters', 'json_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('randallbrenes_dnd_monsters', 'json_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_table('danielmadriz_monsters')
    op.drop_table('danielmadriz_allmonsters')
    # ### end Alembic commands ###
