"""andresnboza migration

Revision ID: c7c65440f575
Revises: bac07e2df5a7
Create Date: 2025-08-27 19:44:14.168134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7c65440f575'
down_revision: Union[str, Sequence[str], None] = 'bac07e2df5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('andresnboza_monster',
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('armor_class', sa.String(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('hit_dice', sa.String(), nullable=True),
    sa.Column('hit_points_roll', sa.String(), nullable=True),
    sa.Column('speed', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.alter_column('randallbrenes_dnd_monsters', 'json_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('randallbrenes_dnd_monsters', 'json_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_table('andresnboza_monster')
    # ### end Alembic commands ###
