from marshmallow import Schema, fields

class MonsterResponseSchema(Schema):
    id = fields.Int()
    index = fields.Str()
    name = fields.Str()
    size = fields.Str()
    type = fields.Str()
    alignment = fields.Str()
    armor_class = fields.List(fields.Dict())
    hit_points = fields.Int()
    hit_dice = fields.Str()
    hit_points_roll = fields.Str()
    speed = fields.Dict()
    strength = fields.Int()
    dexterity = fields.Int()
    constitution = fields.Int()
    intelligence = fields.Int()
    wisdom = fields.Int()
    charisma = fields.Int()
    proficiencies = fields.List(fields.Dict())
    damage_vulnerabilities = fields.List(fields.Str())
    damage_resistances = fields.List(fields.Str())
    damage_immunities = fields.List(fields.Str())
    condition_immunities = fields.List(fields.Str())
    senses = fields.Dict()
    languages = fields.Str()
    challenge_rating = fields.Int()
    proficiency_bonus = fields.Int()
    xp = fields.Int()
    special_abilities = fields.List(fields.Dict())
    actions = fields.List(fields.Dict())
    legendary_actions = fields.List(fields.Dict())
    image = fields.Str()
    url = fields.Str()
    updated_at = fields.Str()
    forms = fields.List(fields.Dict())
    reactions = fields.List(fields.Dict())
