"""Create randymorales people finder tables

Revision ID: 56fbc6ca240b
Revises:
Create Date: 2025-09-03 23:05:18.635468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56fbc6ca240b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('randymorales_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randymorales_family_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['randymorales_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randymorales_favorite_foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['randymorales_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randymorales_hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('hobby', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['randymorales_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randymorales_physical_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('eye_color', sa.String(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['randymorales_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randymorales_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['randymorales_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('randymorales_studies')
    op.drop_table('randymorales_physical_data')
    op.drop_table('randymorales_hobbies')
    op.drop_table('randymorales_favorite_foods')
    op.drop_table('randymorales_family_relations')
    op.drop_table('randymorales_people')
    # ### end Alembic commands ###
