"""ex02 create people tables

Revision ID: 69344a4a39c4
Revises: 7ef45369cdaa
Create Date: 2025-08-31 16:20:54.376982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69344a4a39c4'
down_revision: Union[str, Sequence[str], None] = '7ef45369cdaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_age'), 'people', ['age'], unique=False)
    op.create_index('ix_people_color_age_nat', 'people', ['eye_color', 'hair_color', 'age', 'nationality'], unique=False)
    op.create_index(op.f('ix_people_eye_color'), 'people', ['eye_color'], unique=False)
    op.create_index(op.f('ix_people_hair_color'), 'people', ['hair_color'], unique=False)
    op.create_index(op.f('ix_people_nationality'), 'people', ['nationality'], unique=False)
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_person_id'), 'family', ['person_id'], unique=False)
    op.create_index(op.f('ix_family_relation'), 'family', ['relation'], unique=False)
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'food', name='uq_person_food')
    )
    op.create_index(op.f('ix_favorite_food'), 'favorite', ['food'], unique=False)
    op.create_index(op.f('ix_favorite_person_id'), 'favorite', ['person_id'], unique=False)
    op.create_table('hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('hobby', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'hobby', name='uq_person_hobby')
    )
    op.create_index(op.f('ix_hobbies_hobby'), 'hobbies', ['hobby'], unique=False)
    op.create_index(op.f('ix_hobbies_person_id'), 'hobbies', ['person_id'], unique=False)
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_degree'), 'studies', ['degree'], unique=False)
    op.create_index(op.f('ix_studies_institution'), 'studies', ['institution'], unique=False)
    op.create_index(op.f('ix_studies_person_id'), 'studies', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studies_person_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_institution'), table_name='studies')
    op.drop_index(op.f('ix_studies_degree'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_hobbies_person_id'), table_name='hobbies')
    op.drop_index(op.f('ix_hobbies_hobby'), table_name='hobbies')
    op.drop_table('hobbies')
    op.drop_index(op.f('ix_favorite_person_id'), table_name='favorite')
    op.drop_index(op.f('ix_favorite_food'), table_name='favorite')
    op.drop_table('favorite')
    op.drop_index(op.f('ix_family_relation'), table_name='family')
    op.drop_index(op.f('ix_family_person_id'), table_name='family')
    op.drop_table('family')
    op.drop_index(op.f('ix_people_nationality'), table_name='people')
    op.drop_index(op.f('ix_people_hair_color'), table_name='people')
    op.drop_index(op.f('ix_people_eye_color'), table_name='people')
    op.drop_index('ix_people_color_age_nat', table_name='people')
    op.drop_index(op.f('ix_people_age'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
